alter table public.user_profiles
  drop constraint if exists user_profiles_role_check;

alter table public.user_profiles
  add constraint user_profiles_role_check
  check (role = any (array['TRABAJADOR'::text,'COORDINADOR'::text,'SUPERVISOR'::text,'ADMINISTRADOR'::text]));

alter table public.user_profiles
  add column if not exists warehouse text,
  add column if not exists project text,
  add column if not exists group_name text,
  add column if not exists position text;

create table if not exists public.bulk_user_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text,
  total_rows integer not null default 0,
  created_count integer not null default 0,
  skipped_count integer not null default 0,
  error_count integer not null default 0,
  status text not null default 'COMPLETADO'
    check (status in ('PROCESANDO','COMPLETADO','CON_ERRORES','ERROR')),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.bulk_user_imports enable row level security;

drop policy if exists "bulk_imports_admin_select" on public.bulk_user_imports;
create policy "bulk_imports_admin_select"
on public.bulk_user_imports for select
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;

drop policy if exists "audit_admin_select" on public.audit_log;
create policy "audit_admin_select"
on public.audit_log for select
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create index if not exists bulk_user_imports_created_by_idx
  on public.bulk_user_imports(created_by);

create index if not exists audit_log_actor_idx
  on public.audit_log(actor_user_id);

drop policy if exists "profiles_select_own_or_manager" on public.user_profiles;
create policy "profiles_select_own_or_manager"
on public.user_profiles for select
to authenticated
using (
  (select auth.uid()) = user_id
  or (select private.current_user_komtrol_role()) in ('COORDINADOR','SUPERVISOR','ADMINISTRADOR')
);

drop policy if exists "incidents_select_authenticated" on public.incidents;
create policy "incidents_select_authenticated"
on public.incidents for select
to authenticated
using (
  created_by = (select auth.uid())
  or (select private.current_user_komtrol_role()) in ('COORDINADOR','SUPERVISOR','ADMINISTRADOR')
);

drop policy if exists "notifications_select_role" on public.email_notifications;
create policy "notifications_select_role"
on public.email_notifications for select
to authenticated
using (
  created_by = (select auth.uid())
  or (select private.current_user_komtrol_role()) in ('COORDINADOR','SUPERVISOR','ADMINISTRADOR')
);

drop policy if exists "incident_attachments_select_role" on public.incident_attachments;
create policy "incident_attachments_select_role"
on public.incident_attachments for select
to authenticated
using (
  uploaded_by = (select auth.uid())
  or (select private.current_user_komtrol_role()) in ('COORDINADOR','SUPERVISOR','ADMINISTRADOR')
);
