alter table public.materials
  add column if not exists center text,
  add column if not exists previous_location text,
  add column if not exists location_changed_at timestamptz;

create index if not exists materials_center_idx
  on public.materials(center);

create index if not exists materials_location_changed_at_idx
  on public.materials(location_changed_at desc);

create table if not exists public.material_location_history (
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.materials(id) on delete cascade,
  material_no text not null,
  center text,
  warehouse text,
  previous_location text,
  new_location text,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now()
);

alter table public.material_location_history enable row level security;

create index if not exists material_location_history_material_idx
  on public.material_location_history(material_id, changed_at desc);

create index if not exists material_location_history_material_no_idx
  on public.material_location_history(material_no, changed_at desc);

drop policy if exists "material_location_history_admin_select"
  on public.material_location_history;

create policy "material_location_history_admin_select"
on public.material_location_history
for select
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

grant select on public.material_location_history to authenticated;

drop policy if exists "material_location_history_admin_insert"
  on public.material_location_history;

create policy "material_location_history_admin_insert"
on public.material_location_history
for insert
to authenticated
with check (
  (select private.current_user_komtrol_role()) = 'ADMINISTRADOR'
  and changed_by = (select auth.uid())
);

grant insert on public.material_location_history to authenticated;

create or replace function private.track_material_location_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.location is distinct from old.location then
    new.previous_location := old.location;
    new.location_changed_at := now();

    insert into public.material_location_history (
      material_id,
      material_no,
      center,
      warehouse,
      previous_location,
      new_location,
      changed_by,
      changed_at
    )
    values (
      old.id,
      old.material_no,
      new.center,
      new.warehouse,
      old.location,
      new.location,
      new.updated_by,
      new.location_changed_at
    );
  end if;

  return new;
end;
$$;

revoke all on function private.track_material_location_change() from public;
grant execute on function private.track_material_location_change() to authenticated;

drop trigger if exists trg_track_material_location_change
  on public.materials;

create trigger trg_track_material_location_change
before update of location
on public.materials
for each row
execute function private.track_material_location_change();