create or replace function private.current_user_warehouse()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select up.warehouse
  from public.user_profiles up
  where up.user_id = auth.uid() and up.active = true
  limit 1
$$;

revoke all on function private.current_user_warehouse() from public;
grant usage on schema private to authenticated;
grant execute on function private.current_user_warehouse() to authenticated;

drop policy if exists "profiles_select_own_or_manager" on public.user_profiles;
create policy "profiles_select_own_or_manager"
on public.user_profiles for select
to authenticated
using (
  (select auth.uid()) = user_id
  or (select private.current_user_komtrol_role()) in ('SUPERVISOR','ADMINISTRADOR')
  or (
    (select private.current_user_komtrol_role()) = 'COORDINADOR'
    and warehouse is not distinct from (select private.current_user_warehouse())
  )
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  task_no text not null unique,
  work_type text not null default 'TAREA'
    check (work_type in ('TAREA','RELEVO','PERSONAL')),
  title text not null,
  description text,
  warehouse text,
  project text,
  group_name text,
  responsible_id uuid references auth.users(id),
  created_by uuid not null references auth.users(id),
  category text,
  tags text[] not null default '{}',
  priority text not null default 'MEDIA'
    check (priority in ('BAJA','MEDIA','ALTA','URGENTE')),
  status text not null default 'PENDIENTE'
    check (status in ('PENDIENTE','EN_PROCESO','BLOQUEADO','CERRADO','VENCIDA')),
  progress smallint not null default 0 check (progress between 0 and 100),
  start_at timestamptz,
  due_at timestamptz,
  closed_at timestamptz,
  estimated_hours numeric(10,2),
  email_subject text,
  email_related boolean not null default false,
  extensions_count integer not null default 0,
  original_due_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

create index if not exists tasks_created_by_idx on public.tasks(created_by);
create index if not exists tasks_responsible_idx on public.tasks(responsible_id);
create index if not exists tasks_warehouse_idx on public.tasks(warehouse);
create index if not exists tasks_due_at_idx on public.tasks(due_at);
create index if not exists tasks_status_idx on public.tasks(status);
create index if not exists tasks_work_type_idx on public.tasks(work_type);

drop policy if exists "tasks_select_scope" on public.tasks;
create policy "tasks_select_scope"
on public.tasks for select
to authenticated
using (
  created_by = (select auth.uid())
  or responsible_id = (select auth.uid())
  or (select private.current_user_komtrol_role()) in ('SUPERVISOR','ADMINISTRADOR')
  or (
    (select private.current_user_komtrol_role()) = 'COORDINADOR'
    and warehouse is not distinct from (select private.current_user_warehouse())
  )
);

drop policy if exists "tasks_insert_authenticated" on public.tasks;
create policy "tasks_insert_authenticated"
on public.tasks for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and exists (
    select 1 from public.user_profiles p
    where p.user_id = (select auth.uid()) and p.active = true
  )
);

drop policy if exists "tasks_update_scope" on public.tasks;
create policy "tasks_update_scope"
on public.tasks for update
to authenticated
using (
  created_by = (select auth.uid())
  or responsible_id = (select auth.uid())
  or (select private.current_user_komtrol_role()) = 'ADMINISTRADOR'
  or (
    (select private.current_user_komtrol_role()) = 'COORDINADOR'
    and warehouse is not distinct from (select private.current_user_warehouse())
  )
)
with check (
  created_by = (select auth.uid())
  or responsible_id = (select auth.uid())
  or (select private.current_user_komtrol_role()) = 'ADMINISTRADOR'
  or (
    (select private.current_user_komtrol_role()) = 'COORDINADOR'
    and warehouse is not distinct from (select private.current_user_warehouse())
  )
);

drop policy if exists "tasks_delete_scope" on public.tasks;
create policy "tasks_delete_scope"
on public.tasks for delete
to authenticated
using (
  created_by = (select auth.uid())
  or (select private.current_user_komtrol_role()) = 'ADMINISTRADOR'
);

create table if not exists public.task_history (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.tasks(id) on delete cascade,
  action text not null,
  field_name text,
  old_value text,
  new_value text,
  note text,
  changed_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.task_history enable row level security;
create index if not exists task_history_task_idx on public.task_history(task_id);
create index if not exists task_history_changed_by_idx on public.task_history(changed_by);

drop policy if exists "task_history_select_scope" on public.task_history;
create policy "task_history_select_scope"
on public.task_history for select
to authenticated
using (
  exists (
    select 1 from public.tasks t
    where t.id = task_id
      and (
        t.created_by = (select auth.uid())
        or t.responsible_id = (select auth.uid())
        or (select private.current_user_komtrol_role()) in ('SUPERVISOR','ADMINISTRADOR')
        or (
          (select private.current_user_komtrol_role()) = 'COORDINADOR'
          and t.warehouse is not distinct from (select private.current_user_warehouse())
        )
      )
  )
);

drop policy if exists "task_history_insert_authenticated" on public.task_history;
create policy "task_history_insert_authenticated"
on public.task_history for insert
to authenticated
with check (changed_by = (select auth.uid()));

create table if not exists public.task_comments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  comment text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.task_comments enable row level security;
create index if not exists task_comments_task_idx on public.task_comments(task_id);

drop policy if exists "task_comments_select_scope" on public.task_comments;
create policy "task_comments_select_scope"
on public.task_comments for select
to authenticated
using (
  exists (
    select 1 from public.tasks t
    where t.id = task_id
      and (
        t.created_by = (select auth.uid())
        or t.responsible_id = (select auth.uid())
        or (select private.current_user_komtrol_role()) in ('SUPERVISOR','ADMINISTRADOR')
        or (
          (select private.current_user_komtrol_role()) = 'COORDINADOR'
          and t.warehouse is not distinct from (select private.current_user_warehouse())
        )
      )
  )
);

drop policy if exists "task_comments_insert_authenticated" on public.task_comments;
create policy "task_comments_insert_authenticated"
on public.task_comments for insert
to authenticated
with check (created_by = (select auth.uid()));

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.categories enable row level security;

drop policy if exists "categories_select_authenticated" on public.categories;
create policy "categories_select_authenticated"
on public.categories for select
to authenticated
using (true);

drop policy if exists "categories_admin_write" on public.categories;
create policy "categories_admin_write"
on public.categories for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

insert into public.categories (name, active)
values ('INFORMATIVO', true)
on conflict (name) do nothing;
