create table if not exists public.warehouses (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.warehouses enable row level security;

drop policy if exists "warehouses_select_authenticated" on public.warehouses;
create policy "warehouses_select_authenticated"
on public.warehouses for select
to authenticated
using (true);

drop policy if exists "warehouses_admin_write" on public.warehouses;
create policy "warehouses_admin_write"
on public.warehouses for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  warehouse_code text,
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.projects enable row level security;

drop policy if exists "projects_select_authenticated" on public.projects;
create policy "projects_select_authenticated"
on public.projects for select
to authenticated
using (true);

drop policy if exists "projects_admin_write" on public.projects;
create policy "projects_admin_write"
on public.projects for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.operational_groups (
  id uuid primary key default gen_random_uuid(),
  project_code text,
  name text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (project_code, name)
);
alter table public.operational_groups enable row level security;

drop policy if exists "groups_select_authenticated" on public.operational_groups;
create policy "groups_select_authenticated"
on public.operational_groups for select
to authenticated
using (true);

drop policy if exists "groups_admin_write" on public.operational_groups;
create policy "groups_admin_write"
on public.operational_groups for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

insert into public.operational_groups (project_code, name)
values (null,'PALAS'), (null,'CAMIONES')
on conflict do nothing;

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  material_no text not null,
  stock_code text,
  description text not null,
  location text,
  warehouse text,
  price numeric(16,2),
  notes text,
  status text not null default 'ACTIVO'
    check (status in ('ACTIVO','INACTIVO','OBSERVADO')),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (material_no, warehouse)
);
alter table public.materials enable row level security;

create index if not exists materials_material_idx on public.materials(material_no);
create index if not exists materials_stock_code_idx on public.materials(stock_code);
create index if not exists materials_warehouse_idx on public.materials(warehouse);
create index if not exists materials_location_idx on public.materials(location);

drop policy if exists "materials_select_authenticated" on public.materials;
create policy "materials_select_authenticated"
on public.materials for select
to authenticated
using (true);

drop policy if exists "materials_admin_write" on public.materials;
create policy "materials_admin_write"
on public.materials for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.material_history (
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.materials(id) on delete cascade,
  action text not null,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.material_history enable row level security;
create index if not exists material_history_material_idx on public.material_history(material_id);

drop policy if exists "material_history_admin_select" on public.material_history;
create policy "material_history_admin_select"
on public.material_history for select
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

drop policy if exists "material_history_admin_insert" on public.material_history;
create policy "material_history_admin_insert"
on public.material_history for insert
to authenticated
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR' and changed_by = (select auth.uid()));

create table if not exists public.bulk_imports (
  id uuid primary key default gen_random_uuid(),
  import_type text not null,
  file_name text,
  period text,
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  error_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  status text not null default 'COMPLETADO'
    check (status in ('VALIDANDO','LISTO','COMPLETADO','CON_ERRORES','ERROR')),
  details jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.bulk_imports enable row level security;
create index if not exists bulk_imports_created_by_idx on public.bulk_imports(created_by);
create index if not exists bulk_imports_type_idx on public.bulk_imports(import_type);

drop policy if exists "bulk_imports_admin_all" on public.bulk_imports;
create policy "bulk_imports_admin_all"
on public.bulk_imports for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.kpi_targets (
  id uuid primary key default gen_random_uuid(),
  indicator text not null,
  year integer not null check (year between 2020 and 2100),
  month integer not null check (month between 1 and 12),
  warehouse text not null default 'GLOBAL',
  target numeric(18,4) not null,
  unit text not null default '%',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (indicator, year, month, warehouse)
);
alter table public.kpi_targets enable row level security;

drop policy if exists "kpi_targets_select_authenticated" on public.kpi_targets;
create policy "kpi_targets_select_authenticated"
on public.kpi_targets for select
to authenticated
using (true);

drop policy if exists "kpi_targets_admin_write" on public.kpi_targets;
create policy "kpi_targets_admin_write"
on public.kpi_targets for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');

create table if not exists public.periods (
  id uuid primary key default gen_random_uuid(),
  period text not null,
  warehouse text not null default 'GLOBAL',
  status text not null default 'ABIERTO'
    check (status in ('ABIERTO','CERRADO')),
  closed_by uuid references auth.users(id),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (period, warehouse)
);
alter table public.periods enable row level security;

drop policy if exists "periods_select_authenticated" on public.periods;
create policy "periods_select_authenticated"
on public.periods for select
to authenticated
using (true);

drop policy if exists "periods_admin_write" on public.periods;
create policy "periods_admin_write"
on public.periods for all
to authenticated
using ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR')
with check ((select private.current_user_komtrol_role()) = 'ADMINISTRADOR');
