insert into public.warehouses (code,name,warehouse_scope,remote_group,active)
values
  ('ANTAPACAY_KMMP','ANTAPACAY KMMP','REMOTO','PROYECTO_MINERO',true),
  ('ANTAPACAY_DCP','ANTAPACAY DCP','REMOTO','PROYECTO_MINERO',true),
  ('TOQUEPALA_KMMP','TOQUEPALA KMMP','REMOTO','PROYECTO_MINERO',true),
  ('TOQUEPALA_DCP','TOQUEPALA DCP','REMOTO','PROYECTO_MINERO',true),
  ('CUAJONE_KMMP','CUAJONE KMMP','REMOTO','PROYECTO_MINERO',true),
  ('CUAJONE_DCP','CUAJONE DCP','REMOTO','PROYECTO_MINERO',true),
  ('BAYOVAR_KMMP','BAYOVAR KMMP','REMOTO','PROYECTO_MINERO',true),
  ('BAYOVAR_DCP','BAYOVAR DCP','REMOTO','PROYECTO_MINERO',true),
  ('ANTAMINA_KMMP','ANTAMINA KMMP','REMOTO','PROYECTO_MINERO',true),
  ('ANTAMINA_DCP','ANTAMINA DCP','REMOTO','PROYECTO_MINERO',true),
  ('LAS_BAMBAS_KMMP','LAS BAMBAS KMMP','REMOTO','PROYECTO_MINERO',true),
  ('LAS_BAMBAS_DCP','LAS BAMBAS DCP','REMOTO','PROYECTO_MINERO',true),
  ('QUELLAVECO_DCP','QUELLAVECO DCP','REMOTO','PROYECTO_MINERO',true),

  ('CAJAMARCA_KMMP','CAJAMARCA KMMP','REMOTO','SUCURSAL',true),
  ('CAJAMARCA_DCP','CAJAMARCA DCP','REMOTO','SUCURSAL',true),
  ('PIURA_KMMP','PIURA KMMP','REMOTO','SUCURSAL',true),
  ('PIURA_DCP','PIURA DCP','REMOTO','SUCURSAL',true),
  ('IQUITOS_KMMP','IQUITOS KMMP','REMOTO','SUCURSAL',true),
  ('TRUJILLO_KMMP','TRUJILLO KMMP','REMOTO','SUCURSAL',true),
  ('TRUJILLO_DCP','TRUJILLO DCP','REMOTO','SUCURSAL',true),
  ('AREQUIPA_KMMP','AREQUIPA KMMP','REMOTO','SUCURSAL',true),
  ('AREQUIPA_CUMMINS','AREQUIPA CUMMINS','REMOTO','SUCURSAL',true),

  ('SAN_LUIS_KMMP','SAN LUIS KMMP','REMOTO','TIENDA',true),
  ('HUANCAYO_KMMP','HUANCAYO KMMP','REMOTO','TIENDA',true),
  ('LOS_OLIVOS_DCP','LOS OLIVOS DCP','REMOTO','TIENDA',true),
  ('ILO','ILO','REMOTO','TIENDA',true),
  ('CHICLAYO_DCP','CHICLAYO DCP','REMOTO','TIENDA',true),
  ('SAN_LUIS_DCP','SAN LUIS DCP','REMOTO','TIENDA',true),
  ('CUZCO','CUZCO','REMOTO','TIENDA',true),
  ('TARAPOTO','TARAPOTO','REMOTO','TIENDA',true),
  ('CHIMBOTE','CHIMBOTE','REMOTO','TIENDA',true),
  ('CHICLAYO','CHICLAYO','REMOTO','TIENDA',true),
  ('TACNA_DCP','TACNA DCP','REMOTO','TIENDA',true),
  ('HUANCAYO_DCP','HUANCAYO DCP','REMOTO','TIENDA',true),

  ('CALLAO','CALLAO','CENTRAL',null,true),
  ('PUCUSANA','PUCUSANA','CENTRAL',null,true)
on conflict (code) do update
set
  name=excluded.name,
  warehouse_scope=excluded.warehouse_scope,
  remote_group=excluded.remote_group,
  active=true,
  updated_at=now();
